name: First Action - Single

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        type: boolean
        description: Debug
        default: false
        required: false
      sample_value:
        type: string
        description: Cualquier valor
        default: ""
        required: false   

jobs: 
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "Hello, world!"
      - name: Second Step
        run: echo "This is the second step!"
  bye-world:
    runs-on: ubuntu-latest
    needs: hello-world
    steps:
      - name: First Step
        run: echo "Bye, world!"