name: First Action - Single

on:
  pull_request:
  push:
    branches:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r code/python/requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover -s code/python -p "*_test.py"
      - name: flake8
        run: flake8 code/python
      - name: bandit
        run: bandit -r code/python

  docker:
      runs-on: ubuntu-latest
      needs: test
      steps:
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: user/app:latest