name: First Action - Single

on:
  pull_request:
  push:
    branches:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: flake8
        run: |
          pip install flake8
          flake8 code/python